minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  # Add packages to exclude from the minimum release age
  - "@mad-c/config"
minimumReleaseAgeExcludePrune: true
trustPolicy: "no-downgrade"
trustPolicyIgnoreAfter: 10080
trustPolicyExcludePrune: true
preferFrozenLockfile: true
ignoreScripts: true
strictDepBuilds: true
engineStrict: false
ignorePnpmfile: true
blockExoticSubdeps: true
allowBuilds:
  # Add packages to allow running build scripts
  dprint: true
